---
# 1. The Secure Virtual Machine Template
apiVersion: rke-machine-config.cattle.io/v1
kind: HarvesterConfig
metadata:
  name: pool1-config
  namespace: fleet-default
spec:
  cpuCount: "2"
  memorySize: "4" 
  diskSize: "40"  
  diskBus: "virtio"
  sshUser: "nagata" 
  
  # Infrastructure IDs
  imageName: "default/image-bc9hx" #default/image-bc9hx
  networkName: "default/vm-network"   
  
  # --- SECURE CLOUD-INIT REFERENCES ---
  # Format is always "namespace/template-name"
  userDataTemplateName: "default/hl-userdata-cloudinit-rke2-longhorn"
  networkDataTemplateName: "default/hl-cloudinit-networkdata-dhcp"

---
# 2. The RKE2 Cluster Definition
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: fleet-deployed-cluster
  namespace: fleet-default
spec:
  kubernetesVersion: v1.34.5+rke2r1
  
  rkeConfig:
    machinePools:
    - name: pool1
      quantity: 3 
      controlPlaneRole: true
      etcdRole: true
      workerRole: true
      machineConfigRef:
        kind: HarvesterConfig
        name: pool1-config
      cloudCredentialSecretName: harvester-credential
      
  machineSelectorConfig:
    - config:
        cloud-provider-name: harvester